version: '3.8' 

services:

  # mongodb:
  #   image: mongo:5.0
  #   ports:
  #     - "27017:27017"
    
  #   volumes:
  #     - ./mongodata:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=dev
  #     - MONGO_INITDB_ROOT_PASSWORD=changeme

  postgres:
    image: postgres:15

    ports: 
      - "5432:5432"
#
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=changeme

  # webapi:
  #   build: .

  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DB_HOST=postgres

  #     # Сервис для разворачивания контейнера с автотестами
  # tests: 
  #   image: mrexpen/planet_olymp_phase1
  #   pull_policy: always
  #   ports:
  #     - "8090:8080"
  #   depends_on:
  #     - webapi
  #   environment:
  #     SERVER_URL: http://webapi:8000
  #     STAGE: all
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа
