version: '3.8' 

services:

  postgres:
    image: postgres:15

    ports: 
      - "5432:5432"

    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=changeme

  webapi:
    build: .

    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
    restart: always

      # Сервис для разворачивания контейнера с автотестами
  tests: 
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:8000
      STAGE: all
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа
