version: '3.8' 

services:

  # mongodb:
  #   image: mongo:5.0
  #   ports:
  #     - "27017:27017"
    
  #   volumes:
  #     - ./mongodata:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=dev
  #     - MONGO_INITDB_ROOT_PASSWORD=changeme

  postgres:
    image: postgres:15

    ports: 
      - "5432:5432"

    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=changeme