version: '3.8' 

services:

  postgres:
    image: postgres:latest

    ports: 
      - "5432:5432"

    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=changeme

  webapi:
    image: webapi
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - POSTGRES_NAME=animal-chipization
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dev
      - POSTGRES_PASS=changeme

  # Сервис для разворачивания контейнера с автотестами
  tests: 
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:8080
      STAGE: all
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа
